/**
 * Constantes
 * Coleccion de variables de las que necesito echar mano frecuentemente
 */

const EVENT_STATES = {
  DRAFT: 'DRAFT',
  LIVE: 'LIVE',
  ENDED: 'ENDED',
  CANCELLED: 'CANCELLED',
};

const EVENT_ROLES = {
  DJ: 'DJ',
  ATTENDEE: 'ATTENDEE',
};

const USER_ROLES = {
  ADMIN: 'DJ',
  DJ: 'DJ',
  ATTENDEE: 'ATTENDEE',
};

const SONG_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  PLAYING: 'PLAYING',
  PLAYED: 'PLAYED',
  SKIPPED: 'SKIPPED',
  REJECTED: 'REJECTED',
};

const EVENT_PERMISSIONS = {
  QUEUE_READ: 'QUEUE_READ',
  QUEUE_EDIT: 'QUEUE_EDIT',
  SONG_SUGGEST: 'SONG_SUGGEST',
  SONG_VOTE: 'SONG_VOTE',
  SONG_APPROVE_REJECT: 'SONG_APPROVE_REJECT',
  PARTICIPANT_KICK: 'PARTICIPANT_KICK',
  PARTICIPANT_BAN: 'PARTICIPANT_BAN',
  EVENT_START: 'EVENT_START',
  EVENT_END: 'EVENT_END',
  EVENT_CANCEL: 'EVENT_CANCEL',
  EVENT_SETTINGS_EDIT: 'EVENT_SETTINGS_EDIT',
  ANALYTICS_READ: 'ANALYTICS_READ',
};

const ACTION_LOG_TYPES = {
  EVENT_START: 'EVENT_START',
  EVENT_END: 'EVENT_END',
  EVENT_CANCEL: 'EVENT_CANCEL',
  PARTICIPANT_KICK: 'PARTICIPANT_KICK',
  PARTICIPANT_BAN: 'PARTICIPANT_BAN',
  PARTICIPANT_UNBAN: 'PARTICIPANT_UNBAN',
  PARTICIPANT_COOLDOWN: 'PARTICIPANT_COOLDOWN',
  SONG_APPROVE: 'SONG_APPROVE',
  SONG_REJECT: 'SONG_REJECT',
  SONG_REMOVE: 'SONG_REMOVE',
  SONG_REORDER: 'SONG_REORDER',
  SONG_SKIP: 'SONG_SKIP',
  SONG_STATUS_CHANGE: 'SONG_STATUS_CHANGE',
  SETTINGS_CHANGE: 'SETTINGS_CHANGE',
};

const SOCKET_EVENTS = {
  CONNECT: 'connect',
  DISCONNECT: 'disconnect',
  ERROR: 'error',

  JOIN_EVENT: 'join_event',
  LEAVE_EVENT: 'leave_event',
  EVENT_STARTED: 'event_started',
  EVENT_ENDED: 'event_ended',
  EVENT_CANCELLED: 'event_cancelled',
  EVENT_UPDATED: 'event_updated',

  SONG_REQUESTED: 'song_requested',
  SONG_APPROVED: 'song_approved',
  SONG_REJECTED: 'song_rejected',
  SONG_PLAYING: 'song_playing',
  SONG_SKIPPED: 'song_skipped',
  QUEUE_UPDATED: 'queue_updated',

  PARTICIPANT_JOINED: 'participant_joined',
  PARTICIPANT_LEFT: 'participant_left',
  PARTICIPANT_KICKED: 'participant_kicked',
  PARTICIPANT_BANNED: 'participant_banned',

  SONG_VOTED: 'song_voted',
  VOTE_UPDATED: 'vote_updated',

  SETTINGS_UPDATED: 'settings_updated',
};

module.exports = {
  EVENT_STATES,
  EVENT_ROLES,
  USER_ROLES,
  SONG_STATUS,
  EVENT_PERMISSIONS,
  ACTION_LOG_TYPES,
  SOCKET_EVENTS,
};
